language: csharp
solution: BT.MicroServices.sln
install:
  - nuget restore BT.MicroServices.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release BT.MicroServices.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/BT.Audit.DomainModel.UnitTests/bin/Release/BT.Audit.DomainModel.UnitTests.dll